config/routes.rb
Rails.application.routes.draw do

  root to: 'services#index'

  devise_for :users

  resources :services, only: [:index, :show] do
    resources :appointments, only: [:create, :new]
  end

  namespace :admin, as: 'admin' do
    root to: "services#index"
    resources :services
    resources :users
    resources :appointments, only: [:index, :show, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :service

  validates :name, presence: true
  validates :email, presence:true
  validates :date, presence: true
  validates :contact, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :appointments

  validates :description, presence:true
  validates :value, presence:true, length: { maximum: 10, too_long: "%{count} Excedido tamanho maximo" }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :cpf, presence:true, length: { is: 11 }, uniqueness: true
  validates :password, presence:true
  validates :password_confirmation, presence:true
end

app/controllers/admin/appointments_controller.rb
module Admin
  class AppointmentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_appointment, only: [:show, :destroy]

    def index
      @appointments = Appointment.all
    end

    def show
    end

    def destroy
      @appointment.destroy

      redirect_to admin_appointments_path
    end

    private

    def find_appointment
      @appointment = Appointment.find(params[:id])
    end
  end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_service, only: [:show, :edit, :update, :destroy]

    def index
      @services = Service.all
    end

    def show
    end

    def new
      @service = Service.new
    end

    def edit
    end

    def create
      @service = Service.new(service_params)

      if @service.save
        redirect_to admin_services_path
      else
        render 'new'
      end
    end

    def update
      if @service.update(service_params)
        redirect_to admin_services_path
      else
        render 'edit'
      end
    end

    def destroy
      @service.destroy

      redirect_to admin_services_path
    end

    private
    def service_params
      params.require(:service).permit(:description, :value, :image)
    end

    def find_service
      @service = Service.find(params[:id])
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def new
      @user = User.new
    end

    def index
      @users = User.all
    end

    def show
    end

    def edit
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to admin_users_path
      else
        render 'new'
      end
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render 'edit'
      end
    end

    def destroy
      @user.destroy

      redirect_to admin_users_path
    end

    private
    def user_params
      params.require(:user).permit(:name, :cpf, :email, :password, :password_confirmation)
    end

    def find_user
      @user = User.find(params[:id])
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_service, only: [:new, :create]

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = @service.appointments.new(appointment_params)

    if @appointment.save
      AppointmentMailer.with(appointment: @appointment, service: @service).confirm_email.deliver_now
      redirect_to services_path
    else
      render 'new'
    end
  end

  private
  def appointment_params
    params.require(:appointment).permit(:name, :email, :date, :contact)
  end

  def find_service
    @service = Service.find(params[:service_id])
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :find_service, only: [:show]

  def index
    @services = Service.all
  end

  def show
  end

  private
  def find_service
    @service = Service.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 mb-3">
  <a class="navbar-brand" href="/admin/services">ADMIN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Usuários
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Listagem", admin_users_path, class:'dropdown-item' %>
          <%= link_to "Criar", new_admin_user_path, class:'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Serviços
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Listagem", admin_services_path, class:'dropdown-item' %>
          <%= link_to "Criar", new_admin_service_path, class:'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item float-right">
        <%= link_to('Agendamentos', admin_appointments_path, class:"nav-link") %>
      </li>
      <li class="nav-item float-right">
        <%= link_to('Sair', destroy_user_session_path, class:"nav-link", method: :delete) %>
      </li>
    </ul>
  </div>
</nav>

app/views/admin/appointments/index.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Lista de Agendamentos:</h2>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nome do contratante</th>
      <th>Email do contratante</th>
      <th>Telefone</th>
      <th>Data</th>
      <th>Serviço</th>
      <th>Ação</th>
    </tr>
  </thead>

  <% @appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.name %></td>
      <td><%= appointment.email %></td>
      <td><%= appointment.contact %></td>
      <td><%= appointment.date %></td>
      <td><%= appointment.service.description %></td>
      <td><%= link_to 'Excluir', admin_appointment_path(appointment),
                      method: :delete,
                      data: { confirm: 'Confirmação' } %></td>
    </tr>
    </tr>
  <% end %>
</table>

app/views/admin/appointments/show.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Detalhes do agendamento:</h2>

<%= image_tag @service.image.url(:medium) %>

<p>
  <strong>Descrição:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @service.value %>
</p>

<%= link_to 'Editar', edit_admin_service_path(@service) %> |
<%= link_to 'Voltar', admin_services_path %>

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service], local: true do |form| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@service.errors.count, "error") %> Erros:
      </h2>
      <ul>
        <% @service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <label>Descrição:</label><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <label>Preço:</label><br>
    <%= form.number_field :value %>
  </p>

  <p>
    <label>Imagem:</label>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/services/edit.html.erb
<%= render :partial => 'admin/navbar' %>

<h2>Editar Serviço:</h2>

<%= render 'form' %>

<%= link_to 'Voltar', admin_services_path %>

app/views/admin/services/index.html.erb
<%= render :partial => 'admin/navbar' %>

<h2>Lista de Serviços:</h2>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Imagem</th>
      <th>Descrição</th>
      <th>Valor</th>
      <th class="text-center">Ação</th>
    </tr>
  </thead>

  <% @services.each do |service| %>
    <tr>
      <td><%= image_tag service.image.url(:thumb) %></td>
      <td><%= service.description %></td>
      <td><%= service.value %></td>
      <td class="d-flex justify-content-around">
        <%= link_to 'Detalhes', admin_service_path(service) %>
        <%= link_to 'Editar', edit_admin_service_path(service) %>
        <%= link_to 'Excluir', admin_service_path(service),
                               method: :delete,
                               data: { confirm: 'Confirmação' } %>
      </td>
    </tr>
    </tr>
  <% end %>
</table>

app/views/admin/services/new.html.erb
<%= render :partial => 'admin/navbar' %>

<h2>Novo Serviço:</h2>

<%= render 'form' %>

<%= link_to 'Voltar', admin_services_path %>

app/views/admin/services/show.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Detalhes do Serviço:</h2>

<%= image_tag @service.image.url(:medium) %>

<p>
  <strong>Descrição:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @service.value %>
</p>

<%= link_to 'Editar', edit_admin_service_path(@service) %> |
<%= link_to 'Voltar', admin_services_path %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <label> Nome: </label>
    <%= form.text_field :name, autofocus: true %>
  </p>

  <p>
    <label> CPF: </label>
    <%= form.text_field :cpf %>
  </p>

  <div class="field">
    <label> Email: </label> <br>
    <%= form.email_field :email, autocomplete: "email" %>
  </div>

  <div class="field">
    <label> Senha: (Necessário redigitar a senha ou uma nova)</label>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> caracteres minimos)</em>
    <% end %><br />
    <%= form.password_field :password, autocomplete: "password" %>
  </div>

  <div class="field">
    <label> Confirme sua senha: </label> <br>
    <%= form.password_field :password_confirmation, autocomplete: "password" %>
  </div>

  <div class="actions mt-2">
    <%= form.submit "Modificar" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Editar Usuário:</h2>

<%= render 'form' %>

<%= link_to 'Voltar', admin_users_path %>

app/views/admin/users/index.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Lista de Usuários:</h2>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Email</th>
      <th class="text-center">Ação</th>
    </tr>
  </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.cpf %></td>
      <td><%= user.email %></td>
      <td class="d-flex justify-content-around">
        <%= link_to 'Detalhes', admin_user_path(user) %>
        <%= link_to 'Editar', edit_admin_user_path(user) %>
        <%= link_to 'Excluir', admin_user_path(user),
                               method: :delete,
                               data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Novo Usuário:</h2>

<%= render 'form' %>

<%= link_to 'Voltar', admin_users_path %>

app/views/admin/users/show.html.erb
<%= render :partial => 'admin/navbar' %>
<h2>Detalhe do Usuário:</h2>
<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @user.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Editar', edit_admin_user_path(@user) %> |
<%= link_to 'Voltar', admin_users_path %>

app/views/appointments/_form.html.erb
<div class="d-flex justify-content-around">
  <div class="col-md-6">
    <%= image_tag @service.image.url(:medium) %>

    <p>
      <strong>Descrição:</strong>
      <%= @service.description %>
    </p>

    <p>
      <strong>Valor:</strong>
      <%= @service.value %>
    </p>
  </div>

  <%= form_with scope: :appointment, url: service_appointments_path, class: "col-md-6", local: true do |form| %>
    <% if @appointment.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@appointment.errors.count, "error") %> Erros:
        </h2>
        <ul>
          <% @appointment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <label>Digite seu nome:</label><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <label>Digite seu email (Voce receberá um email informativo):</label><br>
      <%= form.email_field :email %>
    </p>

    <p>
      <labe>Telefone</labe><br>
      <%= form.text_field :contact %>
    </p>

    <p>
      <label>Data e hora do agendamento:</label>
      <%= form.datetime_select :date %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/appointments/new.html.erb
<%= render :partial => './navbar' %>
<h2>Novo Agendamento</h2>

<%= render 'form' %>

<%= link_to 'Voltar', services_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avaliação YAPAY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render :partial => './header' %>
    <%= yield %>
  </body>
</html>

app/views/services/index.html.erb
<%= render :partial => './navbar' %>
<h2>Lista de Serviços</h2>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Imagem</th>
      <th>Descrição</th>
      <th>Valor</th>
      <th class="text-center">Ação</th>
    </tr>
  </thead>

  <% @services.each do |service| %>
    <tr>
      <td><%= image_tag service.image.url(:thumb) %></td>
      <td><%= service.description %></td>
      <td><%= service.value %></td>
      <td class="d-flex justify-content-around">
        <%= link_to 'Agendar', new_service_appointment_path(service) %>
        <%= link_to 'Detalhes', service_path(service) %>
      </td>
    </tr>
    </tr>
  <% end %>
</table>

app/views/services/show.html.erb
<%= render :partial => './navbar' %>
<h2>Detalhes do serviço</h2>

<%= image_tag @service.image.url(:medium) %>

<p>
  <strong>Descrição:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @service.value %>
</p>

<%= link_to 'Voltar', services_path %>